name: Karan test file

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "13"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Karan test file
        run: yarn create-test-file
      # Commit all changed files back to the repository
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
