name: Build

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: "13"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      # Commit all changed files back to the repository
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
